### ISSUE TITLE
Fix the logging issue for CI of Tests

### ISSUE THREAD

**Issue by jdrager** [monday-night-lights/mnl-api#14]
#!/bin/bash -eo pipefail
. venv/bin/activate
python django/manage.py test
Traceback (most recent call last):
  File "django/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/circleci/repo/django/main/settings.py", line 103, in <module>
    logging.disable(logging.CRITICAL)
NameError: name 'logging' is not defined
Exited with code 1

**Comment by ryangallen** [comment]
Should be all set with this commit https://github.com/monday-night-lights/mnl-api/commit/2b48ee2ab2b6586a7858b7b62a2c2f5fedca9155
